name: Test

on:
  release:
    types: [published]

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.tag_name }}
    - name: Setup node
      uses: actions/setup-node
    - name: Run npm start
      run: npm start
