name: Test

on:
  release:
    types: [published]

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.tag_name }}
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Run npm start
      run: npm start
    - name: Upload artifact
      uses: actions/upload-artifact@v1  
      with:
        name: build
        path: .
