# This is a basic workflow that is manually triggered

name:  Build pull request

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Create template file
      run: echo "# Hello world!" > ./.github/workflows
    - name: Test for the prefix
      uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: '!build'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    - name: Comment a response
      if: steps.check.outputs.triggered == 'true'
      uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: template.md
